package ru.raysmith.notifierbot.model

enum class Location {
    INIT, SETTINGS, MENU, INPUT, SETUP_INTERVAL, INTERVAL_HOUR, INTERVAL_MINUTES, INTERVAL_SECONDS, MESSAGE,
    TIME_START_HOUR, TIME_START_MINUTE, TIME_END_HOUR, TIME_END_MINUTE, LIST, DETAILS
}